// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { ExtendedDatabase } from './database-types';

const SUPABASE_URL = "https://zrnqsfncaqvyyymjsemu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpybnFzZm5jYXF2eXl5bWpzZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTQ3MjEsImV4cCI6MjA1ODk3MDcyMX0.ST-i-iPugkxBJ7PgyPbwJxV5i_gJwdYSgTgvy6jxaMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);